### ISSUE TITLE
Update example

### ISSUE THREAD

**Issue by kennylerma** [as2d/as2d-example#2] opened 2019-10-21 15:01 UTC
Hello @jtenner , the current example isn't working.  Apparently, there is no need for import "allocator/tlsf"; anymore in the assembly/index.ts.  So, I removed it, but now I have 

```
ERROR: Import file '~lib/internal/arraybuffer.ts' not found.
    at parseBacklog (C:\Users\Kenny Lerma\Desktop\as2d-example-master\node_modules\assemblyscript\cli\asc.js:396:34)
```

No sure what I need to do get this running, but would appreciate some help. 
Thanks,
Kenny

**Comment by jtenner** [comment] 2019-10-21 22:15
Right this is because the assemblyscript team decided to rewrite everything. I'm still trying to figure out the best way to rewrite as2d to account for this issue.

I'll make sure this gets worked on soon.

**Comment by kennylerma** [comment] 2019-10-22 01:40
Thanks @jtenner I was thinking that was likely the issue.

**Comment by jtenner** [comment] 2019-10-23 17:51
@kennylerma I'm currently working on the rewrite _just to get things working_ as is. I'm going to branch as2d master tonight and get this all done.

**Comment by jtenner** [comment] 2019-10-23 19:43
One of the problems with the current way things works is it doesn't acknowledge the reference counting garbage collector for strings stored in the canvas object. I'm getting errors like 

```
  ● fillText should change the textBaseline property

    expect(jest.fn()).toBeCalledWith(...expected)

    Expected: "test!", 100, 200, 300
    Received: "  翠!", 100, 200, 300

    Number of calls: 1
```

**Comment by kennylerma** [comment] 2019-10-23 21:38
Thanks for looking into this @jtenner.  I'm hoping to incorporate this into a library that duplicates the functionality of Flash.  So, it will be interesting to see the overall performance in the end.

Again, thanks for having a look at this.

**Comment by kennylerma** [comment] 2019-11-01 14:46
Thanks @jtenner .  I appreciate you working on this.  I'll have a look over the weekend if see if this what I'm ideally looking for.   I"m happy to chat, but no need at the moment while sort things out on my end.

**Comment by jtenner** [comment] 2019-11-01 15:29
Of course! Nothing is ideal, but I can definitely be helpful if you want to try making an engine with this software.

Positives:

- optional simd enabled 2d transforms
- almost exact/comparable performance to browser in the majority of hand tested examples Vs js
- garbage collected memory management in Web Assembly
- in actively maintaining this now, so I can give 1st class bug support

Downsides:

- need to work with a slightly different api than canvas context
- not webgl? But that was by design
- the kinds of optimizations this software provides exist only on the web assembly side and glue code needs to be optimized still

**Comment by jtenner** [comment] 2019-11-05 21:28
@kennylerma Thank you for your interest. Please reach out to me if you have any trouble.

**Comment by kennylerma** [comment] 2019-11-07 14:55
@jtenner just to let you know.  I was able to get the demo working now.  Thanks for the update.  I'm going to play with this. :)

**Comment by jtenner** [comment] 2019-11-07 15:43
Feel free to keep this open. I think you're garunteed you're likely to hit issues and things.

If you would like, I am available via the AssemblyScript slack server and can help you get an invite there to talk about any problem you might have.

**Comment by jtenner** [comment] 2019-11-24 21:04
This is merged. If you have any questions you can contact me via the assemblyscript slack or via discord.  Thank you so much for looking into as2d.

**Closed by jtenner** 2019-11-24 21:04 UTC
Labels: bug, question
