### ISSUE TITLE
CanvasInstruction.Arc does not exist

### ISSUE THREAD

**Issue by AdrianMrn** [as2d/as2d-example#1] opened 2019-03-27 16:46 UTC
I get this error when I run `npm run asbuild`:
```
Fatal: Module::getGlobal: $node_modules/as2d/src/shared/CanvasInstruction/CanvasInstruction.Arc does not exist
```

**Comment by jtenner** [comment] 2019-03-27 17:37
Hey! Thanks for the heads up.

A few things to note:

1. AssemblyScript is currently under a huge change/refactor, and this will affect how `as2d` runs in the future
2. A lot of the dependencies are already outdated like parcel-bundler and typescript. 

I will take a look and update the dependencies to assert that this is working.

**Comment by jtenner** [comment] 2019-03-27 17:41
![image](https://user-images.githubusercontent.com/3761339/55099388-fad31f00-5095-11e9-8e0f-ffc7ce87c7b2.png)

Indeed, it is the case that `CanvasInstruction.Arc` exists, and it looks like a compiler error.

**Comment by jtenner** [comment] 2019-03-27 20:13
Update: This is a problem that was fixed here: https://github.com/AssemblyScript/assemblyscript/issues/541

You can either link AssemblyScript locally like this:

```
git clone https://github.com/AssemblyScript/assemblyscript.git
cd assemblyscript
npm install
npm run clean
npm link
cd myprojectFolder
npm link assemblyscript
```

Or wait for the dist files to be updated when the bug fix occurs.

**Comment by AdrianMrn** [comment] 2019-03-28 08:54
Awesome, thank you so much for the fix @jtenner!!

**Comment by jtenner** [comment] 2019-03-28 10:37
Yeah that's when it last worked. I'll reproduce the error myself and file an issue.

**Comment by jtenner** [comment] 2019-04-01 17:33
Status on this bug. I am intentionally waiting for the runtime branch to be merged on master before I file the issue. There are a very large amount of changes being made to the compiler still and I want to make sure that I don't file an unnecessary bug report.

Also, please feel free to join the conversation on discord. The link to the server is in the readme.

**Comment by AdrianMrn** [comment] 2019-04-01 19:10
Sounds good! I'll join the discord tomorrow :)

**Comment by jtenner** [comment] 2019-04-13 20:50
@AdrianMrn Please download the latest version of as2d to verify the bugs are fixed. I upgraded to the latest version of jest and managed to break over 200 tests in one npm command!

However, they are all fixed now, and you should be able to use the `Arc` instruction now haha.

**Comment by jtenner** [comment] 2019-04-15 04:18
I pushed some changes to the master branch to fix this problem. Closed!

**Closed by jtenner** 2019-04-15 04:18 UTC
Labels: Waiting, bug

**Comment by jtenner** [comment] 2019-11-07 17:36
@AdrianMrn Hey! Just bumping. This is more battle-tested and the AssemblyScript rewrite is done.

I could use some help with testing this software if you're interested.
